# Deterministic Governance Layer Configuration
# Author: WicketWise AI, Last Modified: 2024

# Governance mode: READY, SHADOW, LIVE, KILLED
mode: SHADOW

# Bankroll and exposure limits
bankroll:
  total_bankroll: 100000.0        # Total available bankroll (£100,000)
  max_bankroll_exposure_pct: 5.0  # Max 5% of total bankroll at risk
  per_match_max_pct: 2.0          # Max 2% per match
  per_market_max_pct: 1.0         # Max 1% per market
  per_bet_max_pct: 0.5            # Max 0.5% per single bet

# P&L protection guards
pnl_guards:
  daily_loss_limit_pct: 3.0       # Stop trading if daily losses exceed 3%
  session_loss_limit_pct: 2.0     # Intra-session guardrail at 2%

# Liquidity and execution constraints
liquidity:
  max_fraction_of_available_liquidity: 10.0  # Max 10% of available liquidity
  min_odds_threshold: 1.25                   # Minimum acceptable odds
  max_odds_threshold: 10.0                   # Maximum acceptable odds
  slippage_bps_limit: 50                     # Max 50 basis points slippage

# Operational controls
ops:
  require_dual_approval_threshold_gbp: 2000.0  # Dual approval for bets > £2000
  rate_limit:
    count: 5                # Max 5 bets
    per_seconds: 120        # Per 2 minutes
  kill_switch_enabled: false
  shadow_mode_log_only: true

# Concentration and correlation limits
concentration:
  max_concurrent_markets_per_match: 3
  max_correlation_group_exposure_pct: 1.5

# Compliance and jurisdiction
compliance:
  jurisdiction: "UK"
  allowed_currencies: ["GBP", "USD", "EUR"]
  blocked_markets: []
  require_mfa_for_state_changes: true

# Audit and logging
audit:
  retention_days: 2555  # 7 years for compliance
  hash_algorithm: "sha256"
  enable_hash_chaining: true
  log_level: "INFO"

# Service configuration
service:
  host: "0.0.0.0"
  port: 8001
  workers: 1
  log_level: "INFO"
  enable_metrics: true
